apiVersion: v1
data:
  vault-agent-config.hcl: |
    # Comment this out if running as sidecar instead of initContainer
    exit_after_auth = true

    pid_file = "/home/vault/pidfile"

    auto_auth {
        method "jwt" {
            mount_path = "auth/jwt"
            config = {
                role = "aks-cluster"
                path = "/var/run/secrets/kubernetes.io/serviceaccount/token"
            }
        }

        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
            }
        }
    }

    template {
    destination = "/etc/secrets/config.txt"
    contents = <<EOT
    {{- with secret "secret/data/aad-b2c-admin-api/config" }}
    AZURE_TENANT_ID={{ .Data.data.AZURE_TENANT_ID }}
    AZURE_CLIENT_ID={{ .Data.data.AZURE_CLIENT_ID }}
    AZURE_CLIENT_SECRET={{ .Data.data.AZURE_CLIENT_SECRET }}
    {{- end }}
    EOT
    }
kind: ConfigMap
metadata:
  name: example-vault-agent-config
  namespace: default