apiVersion: v1
kind: Service
metadata:
  name: aad-b2c-admin-api-service
spec:
  selector:
    app: aad-b2c-admin-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer